spring.application.name=runnerz

# PostgreSQL connection info
spring.datasource.url=jdbc:postgresql://localhost:5432/contactdb
spring.datasource.username=your_username
spring.datasource.password=your_password

# JPA / Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# shows SQL queries in console (optional)
spring.jpa.properties.hibernate.format_sql=true

# Server port (choose a port other than 5432)
server.port=8081
